### ISSUE TITLE
Update DOM

### ISSUE THREAD

**Issue by afigienas** [Shopify/twine#29]
Interesting package, but I can't fully understand how it work.
For example, I insert  `<a bind-event-click="addNewRow()">New row</a> ` with javascript. How to make this work, and trigger addNewRow() function after link clicked?

**Comment by qq99** [comment]
Welcome @afigienas :) Please refer to https://github.com/Shopify/twine#usage -- if you don't see your on click action being called (or an error saying `addNewRow` is not defined being produced), then it is likely you don't have Twine initialized yet.
