### ISSUE TITLE
Allow `data-` attrs for valid HTML5

### ISSUE THREAD

**Issue by nwtn** [Shopify/twine#43]
No page that uses Twine is valid HTML because of the custom attributes. I'm not suggesting killing these unprefixed versions, but it would be great if we could alias all of Twine’s attributes (e.g. `bind`, `define`) to data attributes (e.g. `data-bind`, `data-define`). That way any users that care about having valid markup can use the `data-` ones, and those that don’t can continue using the unprefixed versions.

**Comment by pushrax** [comment]
Sounds reasonable to me. Feel free to submit a PR if you feel up to it.
