### ISSUE TITLE
Proposal: array bindings

### ISSUE THREAD

**Issue by DrewMartin** [Shopify/twine#73]
### Problem
Right now we have an awkward way of setting up arrays of objects inside of twine. For instance, if you're on a product page and you want to initialize a list of product variant objects, each with the same keys and different values you've got a few options:

#### Option 1: make the define names unique
When defining each of them you can add some unique key, like the variant id, to the name:
`define="{variant<% variant.id %>: new ProductVariant(...)}"` (optionally `context="variant<% variant.id %>"`)
This isn't great because now you can't loop over the objects easily inside the parent object, and it's pretty ugly because you need to use the generated key everywhere.

#### Option 2: overwrite each object successively and use contexts to access them
Each iteration overwrites the previous object, but keeps it in a closure via `context`:
`define="{variant: new ProductVariant(...)}" context="variant"`
Inside the element with the context everything is bound to the correct variant, but the parent object can't access the different variants except for the last one.

#### Option 3: eval
You can use the slightly hacky `eval` to initialize the array and push to it:
```html
<div define="{variants: []}">
  <% variants.each do |variant| %>
    <div eval="variants.push(new ProductVariant(...));">
```
This works but isn't the most friendly looking. `eval` is basically define, in that it will run arbitrary code, but it does nothing with the return value.

### Proposal
I propose an array syntax for use inside define:
`define="{variants[]: new ProductVariant(...)}"`
when the last two characters of a key to define are `[]` it will create an array with that name if it doesn't exist, or push the object to the end of the array (unless it exists and it's not an array, in which case raise). You can do `context="variants[]"` and it will set the context to be the last thing in the array. 

The biggest downside I see is that it makes it difficult to access the right variant from the array from inside the parent context, which only option 1 from above lets you do. If needed you could definitely do something like this:
```html
<% variants.each_with_index do |variant, i| %>
  <div define="{variants[]: new ProductVariant(...)}">
    <input bind="variants[<% i %>].price">
```

We might be able to have some magic that keeps the correct index around and used implicitly so that you could instead do `<input bind="variants[].price">` and have it point to the correct variant, but I'd have to play around with it. It would also potentially become a mess if things started getting added and removed. Like if you did a partial refresh detecting that all the variants are being replaced and so the array should empty out might be tricky, but maybe that's the developer's responsibility instead of twine's.

Thoughts? Alternatives? Criticisms?
@Shopify/tnt

**Comment by qq99** [comment]
I worry most about partial replacing & when to clear the array, when to replace elements

- pagination, you get 50 new variants, so you want to toss old array
- some other inline update, only 1 row changes, and so you want to keep old array and update 1 element

sounds like it could be tricky?

Is it possible for option 3 to then set up a `context`?

**Comment by DrewMartin** [comment]
Just to be clear options 1, 2, and 3 all work right now, but I think they all have some downsides. The proposal is more to make it clear what the intention of the code is and remove some friction when creating an array of objects. It is possible to use the third option for setting up a context, yes, but you'd have to reference it by its position in the array

I think it's reasonable to leave it up to the developer to clear the array when refreshing. If the parent context is replaced then there's no problem, and if it's just the list being replaced then that's the sort of situation where there's likely a javascript component that should be taking care of clearing it.

**Comment by dan-menard** [comment]
> I think it's reasonable to leave it up to the developer to clear the array when refreshing. If the parent context is replaced then there's no problem, and if it's just the list being replaced then that's the sort of situation where there's likely a javascript component that should be taking care of clearing it.

This very yes. At least in the admin, any complicated refresh like this will have a JS class backing it, and if we were to implement a feature like this with jQ, we'd be on our own for that kind of cleanup anyway.

**Comment by qq99** [comment]
I like the concept and I'm all for making Twine more powerful 👍

**Comment by pushrax** [comment]
I would prefer to not diverge the syntax from JS – right now bindings are evaluated with a simple JS function call.

I do agree this needs to be improved though. Here's a potential idea:

```erb
<div define="{variants: []}">
<% variants.each_with_index do |variant, i| %>
  <div mixin="{variants: {<% i %>: new ProductVariant(...)}}">
    <input bind="variants[<% i %>].price">
```

Where `mixin` means:

```js
obj = eval(properties.mixin)
for (k1 in obj)
  for (k2 in obj[k1])
    context[k1][k2] = obj[k1][k2]
```

**Comment by DrewMartin** [comment]
> I would prefer to not diverge the syntax from JS – right now bindings are evaluated with a simple JS function call.

Yeah the keys would have to be strings for it to work. `define="{'array[]': whatever}"` works.

> I do agree this needs to be improved though. Here's a potential idea:

I'm not crazy about that just because it requires the usage of `<% i %>` which we can definitely avoid. 

> We might be able to have some magic that keeps the correct index around and used implicitly so that you could instead do <input bind="variants[].price"> and have it point to the correct variant

I experimented with this today and it would work. I just need to put something to make it prettier. This is also if accessing things from the array inside twine is a high priority. If it's primarily for use inside a context then just making context be the last thing in the array would work well as a first step.

**Comment by dan-menard** [comment]
> I'm not crazy about that just because it requires the usage of <% i %> which we can definitely avoid.

This is what I like most about @DrewMartin's proposal. The `<% i %>` stuff is clunky, and exactly the kid of thing an abstraction should handle.

**Comment by dfmcphee** [comment]
> This is also if accessing things from the array inside twine is a high priority. If it's primarily for use inside a context then just making context be the last thing in the array would work well as a first step.

I think this is a good question to ask. How often do we actually need or want to do this?

**Comment by pushrax** [comment]
> The <% i %> stuff is clunky, and exactly the kid of thing an abstraction should handle.

I agree with that. I think it's a high priority to keep the syntax valid JS though. Here are more ideas:

```
<% variants.each_with_index do |variant, i| %>
  <div define-array="{variants: {new ProductVariant(...)}}">
    <input bind="variants[variants.length - 1].price">
```

`define-array` would create the array `variants` in the context if necessary, and push to it. `last` would get the last element of the array. Binding is still pretty clunky though. Instead, we could add a magic property that is updated by `define-array`:

```
<% variants.each_with_index do |variant, i| %>
  <div define-array="{variants: {new ProductVariant(...)}}">
    <input bind="variants.last.price">
```

Thoughts?

**Comment by DrewMartin** [comment]
I like `define-array`, however the ways of accessing there wouldn't work. Since `"variants.last.price"` would be evaluated every time things were refreshed it would point to the last at time of evaluation, not time of definition. Every single div created in that loop would end up pointing to the last variant in the list, compared to context which would be set to the last variant in the list at that moment in time. 

I played around with storing some more meta information (alongside bindings and contexts) in https://github.com/Shopify/twine/compare/lookup-index but it's a bit clunky. I think it can be made better by storing it on each element (well each one with any bindings at all on it) similar to how contexts are stored.

**Comment by DrewMartin** [comment]
If we do something like "define-array" we might be able to keep some information around to know that in that situation "variants" is an array and when accessed inside the code that instance should actually only be accessing a very specific variant.

```html
<% variants.each_with_index do |variant, i| %>
  <div define-array="{variants: {new ProductVariant(...)}}">
    <input bind="variants.price">
  </div
```

creates html like
```html
  <div define-array="{variants: {new ProductVariant(...)}}">
    <input bind="variants.price"> // internally gets translated to variants[0]
  </div>
  <div define-array="{variants: {new ProductVariant(...)}}">
    <input bind="variants.price"> // internally gets translated to variants[1]
  </div>
```

**Comment by WillsonSmith** [comment]
@DrewMartin good to close?
