### ISSUE TITLE
Parent object for array constructor?

### ISSUE THREAD

**Issue by chrismanderson** [Shopify/twine#90]
This might be outside the scope of this library, but wanted to run it by you all.

Say I have a list of inventory locations for an item, each with a remaining quantity at the location. If I update the quantity on one location, I want to run some logic to update the quantity on the others.

So, I can currently use Twine to bind updates on individual locations (say, showing the amount changed) 

    <% inventory.locations.each do |location| %>
      <div define="{ location : new LocationInventory(<%= location.remaining %>) }">
        <input bind="remaining" type="number">
        <span bind="location.remaining"></span>
      </div>
    <% end %>

That's all well and good, and is what use Twine now for in a number of cases, and it works great!

What I want however, is to have some parent object that contains all of those individual LocationInventory objects and can maintain a relationship between them (for example, reducing the remaining number in one location should raise the remaining number in another).

I was looking into using the new array constructor for this, and was seeing if I could do something like 

    <section class="inventory" define="{manager : new InventoryManager(<%= inventory %>) }">
      <% inventory.locations.each do |location| %>
        <div define-array="{ locations: { location : new LocationInventory(<%= location.remaining %> } })" context="manager">
          <input bind="remaining" type="number">
          <span bind="location.remaining"></span>
        </div>
      <% end %>
    </section>

but that didn't update affect the `manager` object in any way.

Is this something I can accomplish with Twine in its current state, or is this out of scope for this library?

Thanks!

**Comment by patrickdonovan** [comment]
Hi @chrismanderson. define-array is rather new (and could probably use some better documentation), but you should be able to accomplish what you're looking for. Give this a try:

```
<section class="inventory" define="{manager : new InventoryManager(<%= inventory %>)  }" context="manager">
  <% inventory.locations.each do |location| %>
    <div define-array="{ locations: new LocationInventory(<%= location.remaining %>) }">
      <input bind="remaining" type="number">
      <span bind="location.remaining"></span>
    </div>
  <% end %>
</section>
```

You should get `@locations` available in `manager` as an array of LocationInventory objects.

**Comment by chrismanderson** [comment]
That works great! Thanks so much for the info.
