### ISSUE TITLE
How do you bind to the class name directly?

### ISSUE THREAD

**Issue by clarkewd** [Shopify/twine#97]
Instead of having an array of class names, if you simply wanted the DOM element's class name to be bound to the string value of the context item, how would one do this?

Example:

    window.context.myClassName = 'red'
    <input data-bind-class="myClassName" />

In the above example, I'd just like the element to be understood by the DOM as:

    <input class="red" />

How do you do this?

**Comment by qq99** [comment]
Hi there, great question!  To my surprise `data-bind-attribute` was not documented in the README / demo, but you could approach it like this: 

```html
<div data-bind-attribute="{'class': methodThatReturnsAClassName()}"`
```
